# Generated by Django 3.2.23 on 2024-01-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categary', '0002_fruitsvegetables'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
                ('categary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categary.categary')),
            ],
        ),
        migrations.DeleteModel(
            name='fruitsVegetables',
        ),
    ]
