# Generated by Django 3.2.23 on 2024-02-21 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categary', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4eaea328-6df6-42f2-b423-fc6893589018'), editable=False, primary_key=True, serialize=False),
        ),
    ]
