# Generated by Django 3.2.23 on 2024-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categary', '0009_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
