# Generated by Django 3.2.23 on 2024-01-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
